name: coffeeshop_uts
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_13.png
  - assets/vectors/wi_fi_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/time_1_x2.svg
  - assets/vectors/cellular_2_x2.svg
  - assets/images/image_10.png
  - assets/images/image_12.png
  - assets/images/image_11.png
  - assets/images/rectangle_1706.png
  - assets/images/rectangle_1707.png
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/wi_fi_2_x2.svg
  - assets/vectors/add_2_x2.svg
  - assets/vectors/stroke_12_x2.svg
  - assets/vectors/vector_9_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/cellular_1_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/add_x2.svg
  - assets/vectors/add_4_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/search_normal_x2.svg
  - assets/vectors/time_2_x2.svg
  - assets/vectors/bag_2_x2.svg
  - assets/vectors/add_1_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/setting_41_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/images/image_15.png
  - assets/vectors/time_x2.svg
  - assets/vectors/stroke_11_x2.svg
  - assets/vectors/wi_fi_1_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/heart_1_x2.svg
  - assets/vectors/vector_x2.svg
  - assets/vectors/cellular_x2.svg

